image:
  repository: ghcr.io/thedevminertv/johnbakhmat-tech
  pullPolicy: Always
  tag: "main"

replicas: 3

service:
  app_port: 80
  host: john.devminer.xyz
  ssl:
    enabled: true
    port: 443
    issuer:
      name: letsencrypt
      kind: ClusterIssuer

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

# populated by the ArgoCD application
devhosting:
  appname: ''